### ISSUE TITLE
Missing Microsoft.VSSDK.BuildTools.15.7.104

### ISSUE THREAD

**Issue by Neme12** [jcansdale/TemporaryProjects#2]
I'm not able to restore packages for the project (and therefore build) because of this. Looking at https://www.nuget.org/packages/Microsoft.VSSDK.BuildTools/ it seems version 15.7.104 doesn't exist.
@jcansdale  Are you getting this package from another nuget feed? Or is it possible this version was taken down? Thanks

**Comment by jcansdale** [comment]
Thanks for letting me know. It was the version used by the extensibility project wizard. I'll update to the latest and see if that works for you...

![image](https://user-images.githubusercontent.com/11719160/42628809-26daad9a-85c9-11e8-960e-79d035b6e9aa.png)

**Comment by jcansdale** [comment]
@Neme12 updated. Could you pull and see if that fixes it?

btw, PRs are very welcome. 😉

**Comment by jcansdale** [comment]
> Thanks, updating helped. Can you please clarify what you mean by the "extensibility project wizard"? If I create a new VSIX project, there is no wizard.

Sorry, I meant the plain old `VSIXProject` creation. I think there used to be a wizard, but it's now done using `Add  > New Item... > Extensibility`.

**Comment by Neme12** [comment]
Hm, you're right. If I add New Item -> Extensibility -> Custom Command, it adds a reference to version 15.7.104. But if I delete the packages folder and try to restore, it fails.
