### ISSUE TITLE
Publish to Visual Studio Marketplace

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/TemporaryProjects#7]
Should be able to do this using release pipeline. See:
https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-publishing-a-visual-studio-extension-via-command-line?view=vs-2017

> VsixPublisher.exe is the command line tool for publishing Visual Studio extensions to the Marketplace. It can be accessed from ${VSInstallDir}\VSSDK\VisualStudioIntegration\Tools\Bin\VsixPublisher.exe. Commands available on this tool are: publish, createPublisher, deletePublisher, deleteExtension, login, logout.

- Create personal access tokens to authenticate access
https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=vsts#create-personal-access-tokens-to-authenticate-access

I'm having problems creating a personal access token that works. Even if I select all scopes:

![image](https://user-images.githubusercontent.com/11719160/45944585-9ea61a00-bfe2-11e8-844b-18cfde3cd641.png)

I'm getting the following when I try using `VsixPublisher.exe`.

```
VSSDK: error VsixPub0031 : An error occurred while attempting to authenticate:
VS30063: You are not authorized to access https://marketplace.visualstudio.com.
```

Also asked on Gitter:
https://gitter.im/Microsoft/extendvs?at=5ba8a652913ba7799b36c139

**Comment by madskristensen** [comment]
You need to select the “All accessible accounts” option in the dropdown I'm told

**Comment by CartBlanche** [comment]
I'm getting this same error when using Github Actions. Does anyone know what "access" or rights are required for this to work with Github Actions?

**Comment by jcansdale** [comment]
@CartBlanche I've heard you can't create a PAT online any more, you'll probably need to use the API to do it. If you're still blocked, I'll see if I can get more details.

Do you have a link to your Github Actions workflow?

**Comment by CartBlanche** [comment]
@jcansdale I also raised a support ticket, but so far MS support have been next to useless after 12 messages and nearly 14 days later. The GA I'm using can be seen here - https://github.com/WildernessLabs/VS_Win_Meadow_Extension/blob/develop/.github/workflows/dotnet.yml

If you can't access that I'll paste the code here if that helps?

**Comment by jcansdale** [comment]
@CartBlanche I've heard it isn't currently possible to create an "all accessible organisations" PAT, which is required to publish a VSIX to the marketplace. 😞  I'll let you know if I find any more information.

**Comment by prashantvc** [comment]
@CartBlanche Dominique!!! Nice to run into you in here 😄 

You can try the work around suggested in the blog, ping me if the workaround doesn't help
https://devblogs.microsoft.com/devops/issue-with-extension-publishing/

**Comment by CartBlanche** [comment]
Hey @prashantvc Great to see you here! I raised an MS ticket here - https://developercommunity.visualstudio.com/t/Publishing-a-Visual-Studio-Extension-usi/1698068 and frankly the MS support staff haven't helped at all and we have a PAT in place. But it doesn't work for us (I'm doing some work for Meadow, Bryan's start-up) neither from command line of via CI. So any help would be greatly appreciated as that ticket is a month old today.

**Comment by prashantvc** [comment]
I am sorry about it, let me take it up. Hope we can get you unblocked quickly

**Comment by CartBlanche** [comment]
Thanks @prashantvc!!

**Comment by prashantvc** [comment]
@CartBlanche I have replied to the DevComm post, please email vsmarketplace@ms if you continue to have any issue.
I will have someone from engineering to look at it :)

**Comment by CartBlanche** [comment]
@prashantvc I only just saw this message. Thanks I'll get Brian to email them.
